[build]
  publish = "out"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18.17.1"
  NPM_FLAGS = "--prefer-offline --no-audit"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200